//! Acceptance tests for the suite facade (`pith-hash`).
//!
//! Fixture provenance: `tests/fixtures/` is copied byte-exact from the
//! upstream kit's `modhash/tests/fixtures/`, generated by
//! `lab/phash_oracle.py` (Python 3.13 stdlib only) except
//! `base_444.jpg`, which is a byte copy of the jpeg lane's conformance
//! fixture (`modhash-jpeg/tests/fixtures/base_444.jpg`, Pillow 12.3.0
//! encode). `phash_vectors.rs` is the oracle's committed output — the
//! Rust pHash must match it exactly.

mod phash_vectors;

use phash_vectors::PHASH_VECTORS;

use pith_digest::Format;
use pith_hash::{
    Error, Facts, MatchOutcome, Modality, Signature, binary_signature, content_hash, describe,
    detect, match_, signature,
};

fn fixture(name: &str) -> Vec<u8> {
    std::fs::read(format!("tests/fixtures/{name}"))
        .unwrap_or_else(|e| panic!("fixture {name}: {e}"))
}

// ---------------------------------------------------------------------
// Tier 2 image: pHash
// ---------------------------------------------------------------------

/// P6 verify: every committed known-pixel PNG must produce the exact
/// 64-bit hash the independent Python oracle (`lab/phash_oracle.py`)
/// computed and committed to `phash_vectors.rs`. This is an
/// implementation-vs-oracle check, not a self-consistency check.
#[test]
fn phash_matches_python_oracle_exactly() {
    for &(name, want, w, h) in PHASH_VECTORS {
        let desc = describe(&fixture(name)).unwrap_or_else(|e| panic!("{name}: {e}"));
        assert_eq!(desc.modality, Modality::Image, "{name}");
        let Signature::Image(got) = desc.signature else {
            panic!("{name}: not an image signature")
        };
        assert_eq!(
            got, want,
            "{name}: pHash {got:#018x} != oracle {want:#018x}"
        );
        let Facts::Image { width, height, .. } = desc.facts else {
            panic!("{name}: not image facts")
        };
        assert_eq!((width, height), (w, h), "{name}");
    }
}

/// P7 verify: the same pixels carried by JPEG and PNG produce pHashes
/// within Hamming 4 (here: identical, because `base_444.png` is the
/// PNG re-encode of the jpeg lane's byte-exact `.raw` reference). The
/// tier-1 hashes are identical because the decoded pixel streams are.
#[test]
fn jpeg_and_png_of_same_pixels_agree() {
    let jpg = fixture("base_444.jpg");
    let png = fixture("base_444.png");
    assert_eq!(detect(&jpg).format, Format::Jpeg);
    assert_eq!(detect(&png).format, Format::Png);

    let Signature::Image(a) = signature(&jpg).unwrap() else {
        panic!("jpg: not image")
    };
    let Signature::Image(b) = signature(&png).unwrap() else {
        panic!("png: not image")
    };
    let d = pith_digest::hamming(
        &pith_hash::Digest::from_bytes(a.to_be_bytes()),
        &pith_hash::Digest::from_bytes(b.to_be_bytes()),
    );
    assert!(d <= 4, "jpeg-vs-png hamming {d}");

    // Identical pixels -> identical tier-1 content hash.
    assert_eq!(content_hash(&jpg).unwrap(), content_hash(&png).unwrap());
}

/// `match_` between the same image and its self scores Hamming 0 and
/// `matched`; a different image scores a real distance.
#[test]
fn image_match_scores_hamming() {
    let a = signature(&fixture("phash_rgb8_48x40.png")).unwrap();
    let b = signature(&fixture("phash_gray8_40x32.png")).unwrap();
    let same = match_(&a, &a).unwrap();
    assert_eq!(
        same,
        MatchOutcome::Image {
            hamming: 0,
            matched: true
        }
    );
    let diff = match_(&a, &b).unwrap();
    let MatchOutcome::Image { hamming, matched } = diff else {
        panic!("not image outcome")
    };
    assert!(hamming > 10 || !matched, "distinct images should not match");
}

// ---------------------------------------------------------------------
// Tier 1 + tier 2 audio
// ---------------------------------------------------------------------

/// WAV and FLAC encodings of identical PCM produce the same tier-1
/// hash and the same tier-2 signature — the framing pins the rate, so
/// the digests agreeing proves both decoders emit the same `i32` stream.
#[test]
fn wav_and_flac_of_same_pcm_agree() {
    let wav = fixture("tone.wav");
    let flac = fixture("tone.flac");
    assert_eq!(detect(&wav).format, Format::Wav);
    assert_eq!(detect(&flac).format, Format::Flac);
    assert_eq!(content_hash(&wav).unwrap(), content_hash(&flac).unwrap());
    let sa = signature(&wav).unwrap();
    let sb = signature(&flac).unwrap();
    assert_eq!(sa, sb, "wav/flac tier-2 signatures must be identical");

    // And a 22050 Hz sibling hashes differently (rate is in the frame).
    let half_rate = fixture("tone22.wav");
    assert_ne!(
        content_hash(&wav).unwrap(),
        content_hash(&half_rate).unwrap(),
        "rate word must distinguish 44.1 kHz from 22.05 kHz"
    );
}

/// `describe` on audio reports rate/channels/peaks and the match
/// outcome carries the audio Match struct.
#[test]
fn audio_describe_and_match() {
    let wav = fixture("tone.wav");
    let d = describe(&wav).unwrap();
    let Facts::Audio {
        sample_rate,
        channels,
        frames,
        peaks,
    } = d.facts
    else {
        panic!("not audio facts")
    };
    assert_eq!((sample_rate, channels), (44_100, 1));
    assert!(frames > 0 && peaks > 0, "a 1 s tone must yield landmarks");

    // The same content matches itself: modal delta_t = 0.
    let s = signature(&wav).unwrap();
    let out = match_(&s, &s).unwrap();
    let MatchOutcome::Audio { best, matched } = out else {
        panic!("not audio outcome")
    };
    let m = best.expect("self-match must find a hit");
    assert_eq!(m.delta_t, 0);
    assert!(matched, "self-match must pass the vote floor");

    // A WAV at the wrong rate is a named refusal, not a panic.
    match signature(&fixture("tone22.wav")) {
        Err(Error::Audio(_)) => {}
        other => panic!("22050 Hz wav must be Audio::Unsupported, got {other:?}"),
    }
}

// ---------------------------------------------------------------------
// Text
// ---------------------------------------------------------------------

/// NFC and NFD spellings of the same Vietnamese text produce the same
/// tier-1 hash AND the same MinHash signature (kit.md §4). The pinned
/// pair: precomposed `ộ`/`ô` vs `o`/`ộ` spelled with combining marks.
#[test]
fn nfc_nfd_text_agrees_on_both_tiers() {
    // "Tôi yêu tiếng Việt" — NFD spells each vowel as base + combining.
    let nfc = "T\u{00f4}i y\u{00ea}u ti\u{1ebf}ng Vi\u{1ec7}t";
    let nfd = "T\u{006f}\u{0302}i y\u{0065}\u{0302}u ti\u{0065}\u{0302}\u{0301}ng Vi\u{0065}\u{0323}\u{0302}t";
    assert_ne!(nfc, nfd, "the pair must differ byte-for-byte");
    assert_eq!(
        pith_unicode::nfc(nfd),
        nfc,
        "test inputs must be a genuine NFC/NFD pair"
    );

    assert_eq!(
        content_hash(nfc.as_bytes()).unwrap(),
        content_hash(nfd.as_bytes()).unwrap()
    );
    assert_eq!(
        signature(nfc.as_bytes()).unwrap(),
        signature(nfd.as_bytes()).unwrap()
    );
    let j = match_(
        &signature(nfc.as_bytes()).unwrap(),
        &signature(nfd.as_bytes()).unwrap(),
    )
    .unwrap();
    assert_eq!(
        j,
        MatchOutcome::Text {
            jaccard: 1.0,
            matched: true
        }
    );
}

/// Trailing whitespace and case are insignificant in the canonical
/// form; different text keeps different hashes.
#[test]
fn text_canonical_form_is_the_hash_input() {
    let a = content_hash(b"Hello World").unwrap();
    let b = content_hash(b"hello world\n\n\n").unwrap();
    assert_eq!(a, b, "case + trailing whitespace must not matter");
    let c = content_hash(b"hello world!").unwrap();
    assert_ne!(a, c);
    // Text detection: UTF-8 without magic is Modality::Text.
    assert_eq!(detect(b"just some words").modality, Modality::Text);
    assert_eq!(detect(b"just some words").format, Format::Unknown);
}

// ---------------------------------------------------------------------
// Binary
// ---------------------------------------------------------------------

/// Duplicate-file detection through the cross-modal facade: a
/// one-byte-prefixed variant keeps high chunk-set Jaccard but a
/// different tier-1, `match_` carries the chunk-set verdict, and
/// non-UTF-8 bytes land in the binary lane. The file-domain symbol
/// assertions of the upstream copy of this test (chunk-set identity,
/// Jaccard edges, empty-input pins) ported with `binary_signature`
/// itself into `pith-file` (`tests/binary_signature.rs`); this lane
/// keeps only what routes through the facade.
#[test]
fn binary_duplicate_and_near_duplicate() {
    // Deterministic 48 KiB pseudo-file (SplitMix64 bytes).
    let mut rng = pith_digest::SplitMix64::new(0xD15E_5EED);
    let file: Vec<u8> = (0..48 * 1024).map(|_| rng.next_u64() as u8).collect();

    let sig_a = binary_signature(&file).unwrap();
    // The one-byte-prefixed variant: content-defined chunking realigns
    // after the insert, so most chunk digests survive.
    let mut shifted = vec![0xAA];
    shifted.extend_from_slice(&file);
    let sig_c = binary_signature(&shifted).unwrap();
    let j = sig_a.jaccard(&sig_c);
    assert!(
        j > 0.5,
        "prefix-insert variant must keep high Jaccard, got {j}"
    );
    assert_ne!(
        content_hash(&file).unwrap(),
        content_hash(&shifted).unwrap(),
        "tier-1 must differ for different bytes"
    );

    let out = match_(&signature(&file).unwrap(), &signature(&shifted).unwrap()).unwrap();
    let MatchOutcome::Binary { jaccard, matched } = out else {
        panic!("not binary outcome")
    };
    assert_eq!(jaccard, j);
    assert!(matched, "jaccard {jaccard} should pass the 0.5 floor");

    // \xff makes the input non-UTF-8, so the heuristic lands Binary.
    assert_eq!(detect(b"\x00\xff\x02\xfe").modality, Modality::Binary);
}

// ---------------------------------------------------------------------
// describe / match plumbing + error discipline
// ---------------------------------------------------------------------

/// `describe` identifies modality + both tier fields for each modality.
#[test]
fn describe_identifies_every_modality() {
    let img = describe(&fixture("phash_rgb8_48x40.png")).unwrap();
    assert_eq!(img.modality, Modality::Image);
    assert_eq!(img.format, Format::Png);
    assert!(matches!(img.signature, Signature::Image(_)));
    assert!(matches!(img.facts, Facts::Image { .. }));
    assert_ne!(img.tier1, Default::default(), "tier1 must be a real digest");

    let aud = describe(&fixture("tone.wav")).unwrap();
    assert_eq!(aud.modality, Modality::Audio);
    assert!(matches!(aud.signature, Signature::Audio(_)));

    let txt = describe(b"the quick brown fox jumps over the lazy dog").unwrap();
    assert_eq!(txt.modality, Modality::Text);
    assert!(matches!(txt.signature, Signature::Text(_)));
    let Facts::Text { words, .. } = txt.facts else {
        panic!("not text facts")
    };
    assert_eq!(words, 9);

    // \xff forces non-UTF-8 so the ELF-ish header reads as Binary.
    let bin = describe(b"\x7fELF\x02\x01\x01\x00\xff").unwrap();
    assert_eq!(bin.modality, Modality::Binary);
    assert!(matches!(bin.signature, Signature::Binary(_)));

    // Display prints every tier field with the modality name.
    let s = img.to_string();
    assert!(s.contains("modality: image"), "{s}");
    assert!(s.contains("format: png"), "{s}");
    assert!(s.contains("tier1: "), "{s}");
    assert!(s.contains("tier2: phash"), "{s}");
}

/// mp3 decodes through the audio lane (the crate landed while this
/// facade was in flight — the pending slot closed under it). A real
/// fixture proves both tiers; an ID3-tagged non-stream is a named
/// decode error, not a panic.
#[test]
fn mp3_decodes_through_audio_lane() {
    let mp3 = fixture("l3_short.mp3");
    let d = detect(&mp3);
    assert_eq!(
        (d.format, d.modality, d.pending),
        (Format::Mp3, Modality::Audio, false)
    );
    let desc = describe(&mp3).expect("l3_short must describe");
    let Facts::Audio { sample_rate, .. } = desc.facts else {
        panic!("not audio facts")
    };
    assert_eq!(sample_rate, 44_100);
    assert!(matches!(desc.signature, Signature::Audio(_)));

    // An ID3 tag with garbage behind it: detected as mp3, refused by
    // the decoder, modality named.
    let junk = b"ID3\x04\x00\x00\x00\x00\x00\x10".to_vec();
    match signature(&junk) {
        Err(Error::Decode {
            modality: Modality::Audio,
            ..
        }) => {}
        other => panic!("id3 junk must be Decode(audio), got {other:?}"),
    }
    // MPEG frame-sync bytes detect as mp3 without the tag too.
    assert_eq!(detect(&[0xFF, 0xFB, 0x90, 0x00]).format, Format::Mp3);
}

/// mp4 has landed: detection names the video slot, a gutted container
/// is a Decode error naming the video modality, and pdf — the last
/// other landed slot — keeps its own error type. Never a panic, never
/// a silent binary hash.
#[test]
fn landed_slots_report_decode_errors_not_pending() {
    let mut mp4 = vec![0, 0, 0, 0x20];
    mp4.extend_from_slice(b"ftypisom");
    mp4.extend_from_slice(&[0; 24]);
    match signature(&mp4) {
        Err(Error::Decode {
            modality: Modality::Video,
            ..
        }) => {}
        other => panic!("gutted mp4 must be Decode(video), got {other:?}"),
    }
    match content_hash(&mp4) {
        Err(Error::Decode {
            modality: Modality::Video,
            ..
        }) => {}
        other => panic!("mp4 content_hash must be Decode(video), got {other:?}"),
    }

    // pdf's text lane has landed: a gutted container is a Pdf decode
    // error naming the text modality, not an Unsupported refusal.
    let pdf = b"%PDF-1.7\nbody".to_vec();
    match describe(&pdf) {
        Err(Error::Pdf(_)) => {}
        other => panic!("corrupt pdf must be Error::Pdf, got {other:?}"),
    }
}

/// The video lane end to end: an ffmpeg-generated mp4 detects as
/// video, both tiers answer, `describe` reports real frame facts, and
/// the same stream remuxed to mov fingerprints identically.
#[test]
fn mp4_decodes_through_video_lane() {
    let mp4 = fixture("a_64x48.mp4");
    let d = detect(&mp4);
    assert_eq!(
        (d.format, d.modality, d.pending),
        (Format::Mp4, Modality::Video, false)
    );
    let desc = describe(&mp4).expect("a_64x48.mp4 must describe");
    let Facts::Video {
        width,
        height,
        duration_s,
        frames_sampled,
    } = desc.facts
    else {
        panic!("mp4 must report video facts")
    };
    assert_eq!((width, height), (64, 48));
    assert_eq!(duration_s, 4.0);
    assert_eq!(frames_sampled, 8);
    let Signature::Video(v) = &desc.signature else {
        panic!("mp4 must carry a video signature")
    };
    assert_eq!(v.frame_hashes.len(), 8);
    assert_eq!(v.minhash.len(), pith_hash::SIGNATURE_WORDS);
    // Tier-1 the facade reports is the fingerprint's content digest —
    // describe and content_hash agree on the same input.
    assert_eq!(content_hash(&mp4).unwrap(), desc.tier1);

    // The same elementary stream remuxed to mov: identical signature,
    // identical tier-1, match score 1.0 through the facade.
    let mov = signature(&fixture("a_64x48.mov")).unwrap();
    let outcome = match_(&desc.signature, &mov).unwrap();
    let MatchOutcome::Video { score, matched, .. } = outcome else {
        panic!("video match must be MatchOutcome::Video")
    };
    assert_eq!(score, 1.0);
    assert!(matched);

    // A non-AVC video track refuses by name — Unsupported naming the
    // video modality, not a decode panic.
    match signature(&fixture("e_mp4v.mp4")) {
        Err(Error::Decode {
            modality: Modality::Video,
            source: pith_digest::Error::Unsupported(_),
        }) => {}
        other => panic!("mp4v must be Decode(video, Unsupported), got {other:?}"),
    }

    // Display prints the video facts line.
    let s = desc.to_string();
    assert!(s.contains("modality: video"), "{s}");
    assert!(s.contains("video: 64x48px"), "{s}");
}

/// The video lane's per-frame hash is bit-identical to the suite's image
/// pHash on the same luma plane — the two implementations of kit.md §3
/// must agree exactly, since pith-video re-implements the DCT step
/// it cannot import (no pith-math edge in its dependency list).
#[test]
fn video_frame_phash_matches_image_phash() {
    use pith_image::raster::{Gray, Image};
    // A deterministic non-trivial luma plane.
    let mut rng = pith_digest::SplitMix64::new(0xA11);
    let plane: Vec<u8> = (0..64 * 48).map(|_| rng.next_u64() as u8).collect();
    let img = Image::<Gray, u8>::from_vec(64, 48, plane.clone()).unwrap();
    assert_eq!(
        pith_video::frame_phash(64, 48, &plane).unwrap(),
        pith_hash::image_phash(&img).unwrap()
    );
    // A second shape: gradient instead of noise.
    let plane: Vec<u8> = (0..32 * 24).map(|i| ((i * 7) % 256) as u8).collect();
    let img = Image::<Gray, u8>::from_vec(32, 24, plane.clone()).unwrap();
    assert_eq!(
        pith_video::frame_phash(32, 24, &plane).unwrap(),
        pith_hash::image_phash(&img).unwrap()
    );
}

/// pdf extracts its text layer into the text lane: tier-1 hashes the
/// canonicalized extraction, tier-2 signs it with MinHash.
#[test]
fn pdf_text_flows_through_text_lane() {
    let pdf = fixture("text_page.pdf");
    let d = detect(&pdf);
    assert_eq!(
        (d.format, d.modality, d.pending),
        (Format::Pdf, Modality::Text, false)
    );
    let desc = describe(&pdf).expect("text_page.pdf must describe");
    let Facts::Text {
        words,
        canonical_len,
    } = desc.facts
    else {
        panic!("pdf must report text facts")
    };
    assert!(words > 0 && canonical_len > 0, "pdf text must be non-empty");
    assert!(matches!(desc.signature, Signature::Text(_)));
    // Two tier-1 calls agree — extraction is deterministic.
    assert_eq!(content_hash(&pdf).unwrap(), desc.tier1);
}

/// Corrupt claims on implemented formats are Decode errors naming the
/// modality — never a panic, never a wrong-modality answer.
#[test]
fn corrupt_containers_are_named_decode_errors() {
    // Truncated PNG: magic right, file gutted.
    match signature(b"\x89PNG\r\n\x1a\n\x00") {
        Err(Error::Decode {
            modality: Modality::Image,
            ..
        }) => {}
        other => panic!("truncated png must be Decode(image), got {other:?}"),
    }
    // "BM" with no bitmap behind it.
    match describe(b"BM\x00") {
        Err(Error::Decode {
            modality: Modality::Image,
            ..
        }) => {}
        other => panic!("truncated bmp must be Decode(image), got {other:?}"),
    }
    // "fLaC" then nothing.
    match signature(b"fLaC") {
        Err(Error::Decode {
            modality: Modality::Audio,
            ..
        }) => {}
        other => panic!("truncated flac must be Decode(audio), got {other:?}"),
    }
    // RIFF+WAVE truncated mid-header.
    match content_hash(b"RIFF\x04\x00\x00\x00WAVE") {
        Err(Error::Decode {
            modality: Modality::Audio,
            ..
        }) => {}
        other => panic!("truncated wav must be Decode(audio), got {other:?}"),
    }
}

/// Garbage in is a named `Err` or a binary answer — never a panic —
/// across every public entry point.
#[test]
fn garbage_never_panics_anywhere() {
    let mut rng = pith_digest::SplitMix64::new(0xFEED_FACE);
    for i in 0..2000 {
        let len = rng.next_u64() as usize % 512;
        let mut v = Vec::with_capacity(len);
        for _ in 0..len {
            v.push(rng.next_u64() as u8);
        }
        // Also seed with real magics so decoders get partial truth.
        if i % 3 == 0 {
            let magic: &[u8] = match i % 9 {
                0 => b"\x89PNG\r\n\x1a\n",
                1 => b"\xff\xd8\xff\xe0",
                2 => b"BM",
                3 => b"RIFF\x24\x00\x00\x00WAVE",
                4 => b"fLaC",
                5 => b"GIF89a",
                6 => b"PK\x03\x04",
                7 => b"%PDF-1.7\n",
                _ => b"ID3",
            };
            let mut m = magic.to_vec();
            m.extend_from_slice(&v);
            v = m;
        }
        // Any result is fine; a panic is not.
        let _ = signature(&v);
        let _ = describe(&v);
        let _ = content_hash(&v);
        let _ = binary_signature(&v);
    }
}

/// `match_` across modalities is an error, not a zero score.
#[test]
fn match_across_modalities_is_refused() {
    let img = signature(&fixture("phash_rgb8_48x40.png")).unwrap();
    let txt = signature(b"some plain text here").unwrap();
    match match_(&img, &txt) {
        Err(Error::BadValue(_)) => {}
        other => panic!("cross-modality match must be BadValue, got {other:?}"),
    }
}

/// ZIP and GIF have no modality lane in the workspace and fall to
/// binary semantics by rule, not to a pending refusal.
#[test]
fn out_of_vocabulary_formats_fall_back_to_binary() {
    let zip = b"PK\x03\x04\x14\x00\x00\x00\x00\x00";
    let d = detect(zip);
    assert_eq!(
        (d.format, d.modality, d.pending),
        (Format::Zip, Modality::Binary, false)
    );
    // Content: raw bytes hashed + chunked, no refusal.
    assert!(describe(zip).is_ok());
    let gif = b"GIF89a\x01\x00\x01\x00";
    let d = detect(gif);
    assert_eq!(
        (d.format, d.modality, d.pending),
        (Format::Gif, Modality::Binary, false)
    );
    assert!(describe(gif).is_ok());
}
