//! Acceptance tests for `pith-hash-cli` (phase P18).
//!
//! The dedup ground-truth test below is the plan's verify clause: a
//! synthesized directory whose cluster labels are known by construction
//! must come back with exactly those labels. Everything is generated by
//! `pith_hash_cli::fixture` (SplitMix64-seeded), so the run is identical
//! on every platform and no fixture files are needed.

use std::path::PathBuf;

use pith_hash_cli::{
    DedupReport, Input, dedup_inputs, distance, fixture, render_description, signature_of,
};

fn input(name: &str, bytes: Vec<u8>) -> Input {
    Input {
        path: PathBuf::from(name),
        bytes,
    }
}

/// Sorts each cluster's members and the cluster list so equality is
/// label-for-label, not order-for-order.
fn normalize(report: &DedupReport) -> Vec<Vec<usize>> {
    let mut groups: Vec<Vec<usize>> = report
        .groups
        .iter()
        .map(|g| {
            let mut m = g.members.clone();
            m.sort_unstable();
            m
        })
        .collect();
    groups.sort_unstable();
    groups
}

/// Four base images × three perturbed variants = 12 inputs, four known
/// clusters. The clusters are known because the generator makes them:
/// bases differ in their low-frequency content (observed pairwise
/// distances 16..38), variants perturb pixels within ±4 (observed
/// distances 0..4), so only same-seed members sit inside the image
/// advisory bound (hamming ≤ 10).
#[test]
fn dedup_recovers_ground_truth_clusters() {
    let seeds = [0xA1u64, 0xA2, 0xA3, 0xA4];
    let mut inputs: Vec<Input> = Vec::new();
    // Interleave bases and variants so input order is not cluster order.
    for variant in 0..3u64 {
        for &seed in &seeds {
            let base = fixture::patterned_pixels(seed, 48, 40);
            let px = if variant == 0 {
                base
            } else {
                fixture::perturb_pixels(&base, seed ^ (variant << 8), 4, 997 + variant)
            };
            let bmp = fixture::bmp24(48, 40, &px);
            inputs.push(input(&format!("s{seed:#x}_v{variant}.bmp"), bmp));
        }
    }
    assert_eq!(inputs.len(), 12);

    let report = dedup_inputs(&inputs, None);
    assert!(
        report.skipped.is_empty(),
        "all inputs must sign: {:?}",
        report.skipped
    );
    assert!(report.singles.is_empty(), "no singles expected");
    assert_eq!(report.groups.len(), 4, "want 4 clusters, got {report:?}");

    // Ground truth: input i = variant (i/4) of seed seeds[i % 4].
    let mut want: Vec<Vec<usize>> = seeds
        .iter()
        .enumerate()
        .map(|(si, _)| (0..12).filter(|&i| i % 4 == si).collect())
        .collect();
    want.sort_unstable();
    assert_eq!(normalize(&report), want, "clusters must match ground truth");

    // Perturbed variants are *not* byte-identical, so groups are
    // perceptual, not exact — the exact flag must honestly say so.
    for g in &report.groups {
        assert!(!g.exact, "perturbed variants must not read as exact");
    }
}

/// The `--threshold` seam: at `distance == threshold` the pair still
/// clusters (inclusive bound); one tick below it does not. This is the
/// predicate `calibrate`'s output feeds.
#[test]
fn dedup_threshold_is_inclusive() {
    // Two patterned bases at a known distance apart.
    let a = fixture::bmp24(48, 40, &fixture::patterned_pixels(0xA1, 48, 40));
    let b = fixture::bmp24(48, 40, &fixture::patterned_pixels(0xA2, 48, 40));
    let sa = signature_of(&a).unwrap();
    let sb = signature_of(&b).unwrap();
    let d = distance(&sa, &sb).unwrap();
    assert!(d > 10, "two distinct bases must exceed the advisory bound");

    let inputs = vec![input("a.bmp", a), input("b.bmp", b)];
    let at = dedup_inputs(&inputs, Some(d));
    assert_eq!(at.groups.len(), 1, "d <= d must cluster (inclusive)");
    assert_eq!(at.groups[0].members, vec![0, 1]);

    let below = dedup_inputs(&inputs, Some(d - 1));
    assert!(below.groups.is_empty(), "d > d-1 must not cluster");
    assert_eq!(below.singles, vec![0, 1]);
}

/// Refused inputs (pending lanes, corrupt containers) land in
/// `skipped` — the report never silently drops a file.
#[test]
fn dedup_reports_skipped_inputs() {
    let mut mp4 = vec![0, 0, 0, 0x20];
    mp4.extend_from_slice(b"ftypisom");
    mp4.extend_from_slice(&[0; 24]);
    let img = fixture::bmp24(8, 8, &fixture::patterned_pixels(0xB1, 8, 8));
    let inputs = vec![
        input("one.bmp", img.clone()),
        input("clip.mp4", mp4),
        input("two.bmp", img),
    ];
    let report = dedup_inputs(&inputs, None);
    assert_eq!(report.skipped, vec![1], "the pending mp4 must be skipped");
    assert_eq!(report.groups.len(), 1, "the two identical bmps cluster");
    assert!(report.groups[0].exact, "identical bytes are exact dupes");
}

/// Binary lane: byte-identical files cluster; a 4 KiB-prefix shift
/// still clusters via content-defined chunking; an unrelated blob is a
/// single.
#[test]
fn dedup_binary_lane() {
    let blob = fixture::binary_blob(0xBEEF, 96 * 1024);
    let mut shifted = vec![0xAA; 4096];
    shifted.extend_from_slice(&blob);
    let other = fixture::binary_blob(0xFACE, 96 * 1024);
    let inputs = vec![
        input("a.bin", blob.clone()),
        input("b.bin", blob),
        input("c.bin", shifted),
        input("d.bin", other),
    ];
    let report = dedup_inputs(&inputs, None);
    assert_eq!(report.groups.len(), 1, "the three related blobs cluster");
    assert_eq!(normalize(&report), vec![vec![0, 1, 2]]);
    assert_eq!(report.singles, vec![3]);
}

/// `describe` must show all three tiers on every modality — the plan's
/// describe contract. The facade prints image tier-3 itself; the CLI
/// adds the explicit `tier3:` row for the other modalities.
#[test]
fn describe_output_lists_three_tiers() {
    let cases: Vec<(&str, Vec<u8>, &str)> = vec![
        (
            "image",
            fixture::bmp24(48, 40, &fixture::patterned_pixels(0xC1, 48, 40)),
            "tier3: orb keypoints=",
        ),
        (
            "audio",
            fixture::wav16(44_100, &fixture::tone(0xC2, 0.5)),
            "tier3:",
        ),
        ("text", fixture::prose(0xC3, 4096).into_bytes(), "tier3:"),
        ("binary", fixture::binary_blob(0xC4, 64 * 1024), "tier3:"),
    ];
    for (name, bytes, needle) in cases {
        let d = pith_hash::describe(&bytes).unwrap_or_else(|e| panic!("{name}: {e}"));
        let text = render_description(&d);
        for tier in ["tier1:", "tier2:", "tier3:"] {
            assert!(text.contains(tier), "{name}: output missing {tier}\n{text}");
        }
        assert!(text.contains(needle), "{name}: missing {needle}\n{text}");
    }
}

/// `distance` is the kit's scalar axis: identical inputs score 0, and
/// the text/binary maps are `round((1 - jaccard) * 1e6)`.
#[test]
fn distance_axes_are_scalar() {
    let ta = signature_of(fixture::prose(0xD1, 4096).as_bytes()).unwrap();
    let tb = signature_of(fixture::prose(0xD1, 4096).as_bytes()).unwrap();
    assert_eq!(distance(&ta, &tb).unwrap(), 0, "identical text scores 0");

    let a = signature_of(&fixture::binary_blob(0xD2, 48 * 1024)).unwrap();
    let b = signature_of(&fixture::binary_blob(0xD3, 48 * 1024)).unwrap();
    let d = distance(&a, &b).unwrap();
    assert!(d >= 900_000, "unrelated blobs sit near 1e6, got {d}");

    // Cross-modality distance is a named error, never a silent 0.
    let img = signature_of(&fixture::bmp24(
        8,
        8,
        &fixture::patterned_pixels(0xD4, 8, 8),
    ))
    .unwrap();
    assert!(distance(&img, &ta).is_err());
}

// ---------------------------------------------------------------------
// Coverage: every per-modality arm of the shared helpers
// ---------------------------------------------------------------------

use pith_hash_cli::{bound_line, is_match, json_string, read_input, score_line};

/// Builds one signature per modality so `distance`, `score_line`,
/// `bound_line` and `is_match` run every arm with real values.
#[test]
fn distance_and_lines_cover_every_modality() {
    let img = signature_of(&fixture::bmp24(
        48,
        40,
        &fixture::patterned_pixels(0xA1, 48, 40),
    ))
    .expect("image");
    let wav = fixture::wav16(44_100, &fixture::tone(0xC2, 0.3));
    let audio = signature_of(&wav).expect("audio");
    let text = signature_of(fixture::prose(0xC3, 2048).as_bytes()).expect("text");
    let binary = signature_of(&fixture::binary_blob(0xC4, 48 * 1024)).expect("binary");
    let video = signature_of(include_bytes!("../../tests/fixtures/a_64x48.mp4")).expect("video");

    for (sig, want_bound) in [
        (&img, "advisory: hamming <= 10"),
        (&audio, "advisory: votes >= 8"),
        (&text, "advisory: jaccard >= 0.8"),
        (&binary, "advisory: jaccard >= 0.5"),
        (&video, "advisory: frames >= 0.8"),
    ] {
        let d = distance(sig, sig).expect("same modality");
        let outcome = pith_hash::match_(sig, sig).expect("match");
        assert!(is_match(&outcome), "self must match");
        assert_eq!(bound_line(&outcome), want_bound);
        assert!(!score_line(&outcome).is_empty());
        // The audio axis is votes-based (larger = closer), so only the
        // distance-shaped axes bottom out at exactly 0 for a self-pair.
        if !matches!(outcome, pith_hash::MatchOutcome::Audio { .. }) {
            assert_eq!(d, 0, "self-distance must be 0");
        }
    }

    // Distance axes disagree across modalities.
    assert!(distance(&img, &text).is_err());
}

/// The audio score line distinguishes the no-candidate shape.
#[test]
fn audio_score_line_reports_missing_candidates() {
    let loud = signature_of(&fixture::wav16(44_100, &fixture::tone(0xC2, 0.3))).expect("loud");
    let silent = signature_of(&fixture::wav16(44_100, &[0i16; 44_100])).expect("silent");
    let outcome = pith_hash::match_(&loud, &silent).expect("match");
    let line = score_line(&outcome);
    assert!(
        line == "score: votes=0" || line.contains("delta_t="),
        "unexpected audio score line: {line}"
    );
    assert!(!is_match(&outcome), "tone vs silence must not match");
}

/// `read_input` surfaces IO errors with the path attached.
#[test]
fn read_input_reports_io_error() {
    let err = match read_input(&PathBuf::from("definitely/not/here.bin")) {
        Ok(_) => panic!("missing file must not read"),
        Err(e) => e,
    };
    assert!(!err.to_string().is_empty());
}

/// JSON escaping covers the six required escapes plus control bytes.
#[test]
fn json_escape_covers_control_characters() {
    assert_eq!(
        json_string("a\"b\\c\nd\te\rf\u{1}g"),
        "\"a\\\"b\\\\c\\nd\\te\\rf\\u0001g\""
    );
}

/// `render_description` walks every modality's tier-3 line.
#[test]
fn render_description_covers_every_modality() {
    let img = render_description(
        &pith_hash::describe(&fixture::bmp24(
            48,
            40,
            &fixture::patterned_pixels(0xA1, 48, 40),
        ))
        .expect("describe"),
    );
    assert!(img.contains("tier3: orb keypoints="), "{img}");

    let audio = render_description(
        &pith_hash::describe(&fixture::wav16(44_100, &fixture::tone(0xC2, 0.3))).expect("describe"),
    );
    assert!(audio.contains("tier3: dtw"), "{audio}");

    for (bytes, tier2) in [
        (fixture::prose(0xC3, 2048).into_bytes(), "minhash"),
        (fixture::binary_blob(0xC4, 48 * 1024), "fastcdc"),
    ] {
        let out = render_description(&pith_hash::describe(&bytes).expect("describe"));
        assert!(out.contains("tier3: none"), "{out}");
        assert!(out.contains(tier2), "{out}");
    }

    let video = render_description(
        &pith_hash::describe(include_bytes!("../../tests/fixtures/a_64x48.mp4").as_slice())
            .expect("describe"),
    );
    assert!(video.contains("tier3: none"), "{video}");
    assert!(video.contains("sampled frames"), "{video}");
}

/// Cross-modality pairs never group: identical texts cluster on the
/// text axis, the image stays a singleton, and the img↔text comparison
/// is skipped rather than scored across axes.
#[test]
fn dedup_never_groups_cross_modality_inputs() {
    let inputs = vec![
        input(
            "img.bmp",
            fixture::bmp24(48, 40, &fixture::patterned_pixels(0xA1, 48, 40)),
        ),
        input("t.txt", fixture::prose(0xC3, 2048).into_bytes()),
        input("t2.txt", fixture::prose(0xC3, 2048).into_bytes()),
    ];
    let report = dedup_inputs(&inputs, None);
    assert_eq!(report.groups.len(), 1, "groups: {}", report.groups.len());
    assert_eq!(report.singles.len(), 1, "singles: {}", report.singles.len());
    assert!(report.skipped.is_empty());
}
